apiVersion: v1
kind: Service
metadata:
  name: springboot-rest-app-svc
spec:
  type: NodePort
  selector:
     app: springboot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30786